### ISSUE TITLE
[US-07] Bookmarks

### ISSUE THREAD

**Issue by saschacollinet** [saschacollinet/capstone-project#14]
### Value Statement (User Story)

As a user
I want to bookmark activities
in order to display them on a seperate page

### Acceptance criteria

- [x] The bookmark button renders on every card
- [x] On click onto the bookmark button it changes its style to show that a card is bookmarked
- [x] Bookmarked cards render on a new page 
- [x] The bookmarks page is accessible via the navigation menu

### Tasks

- [x] Create feature branch
- [x] Build bookmark button
- [x] Write bookmark function
- [x] Implement function that bookmarks are rendered in a new route
- [x] Add new navlink for the new route to navigation menu
- [x] Add all compnenets to the app
- [ ] Write tests for the components
- [x] Add styles

### Complexity (low, medium, high)

medium
