### ISSUE TITLE
[US-08] Map

### ISSUE THREAD

**Issue by saschacollinet** [saschacollinet/capstone-project#15]
### Value Statement (User Story)

As a user
I want a map
in order to display activities around me

### Acceptance criteria

- [x] The map is reachable through the burger menu
- [x] All activities render as markers on their relevant position on the map
- [x] You can toggle details for the activitiy within the marker
- [x] The bookmark button renders on every marker and works the same way as before

### Tasks

- [x] Create feature branch
- [x] Build map componenet
- [x] Build marker component
- [x] Link both components
- [x] Add bookmark button
- [x] Add everythin to the app and add a new route
- [x] Add new navlink for the new route to navigation menu
- [ ] Write tests for the components
- [x] Add styles

### Complexity (low, medium, high)

medium to high
