### ISSUE TITLE
[US-02] Show details of a single event

### ISSUE THREAD

**Issue by saschacollinet** [saschacollinet/capstone-project#2]
### Value Statement (User Story)

As a user
I want to click on a button
in order to show all details for a single event.

### Acceptance criteria

- [ ] On button click details of the relevant event are shown
- [ ] The details should toggle away when the user switches to another card
 
### Tasks
- [ ] Create feature branch
- [ ] Build show more button
- [ ] Build details area
- [ ] Write test for the components
- [ ] Add components to app
 
### Complexity (low, medium, high)
low
