### ISSUE TITLE
[US-05] Burger menu

### ISSUE THREAD

**Issue by saschacollinet** [saschacollinet/capstone-project#3]
### Value Statement (User Story)

As a user
I want a burger menu
in order to navigate between the different pages of the app

### Acceptance criteria

- [x] The menu button renders in the header
- [x] On click of the menu button the menu toggles in and out of view
- [x] The menu contains funtional links to home, the full list and the create form
- [x] On click onto the links only the relvante page renders in main

### Tasks

- [x] Create feature branch
- [x] Create burger menu button
- [x] Create burger menu list elements
- [x] Add function to toggle the menu
- [x] Add relevant routing
- [x] Add all components to app
- [x] Write tests for the components
- [x] Add styles

### Complexity (low, medium, high)

medium
