### ISSUE TITLE
[US-01] Basic landing page

### ISSUE THREAD

**Issue by saschacollinet** [saschacollinet/capstone-project#5]
### Value Statement (User Story)

As a user
I want a basic landing page
in order to be greeted and get basic information about the app

### Acceptance criteria

- [x] App renders Header, Main with Home and Footer
- [x] The user is greeted and gets basic information about the app
 
### Tasks

- [x] Create feature branch
- [x] Build Header with a headline
- [x] Build Main
- [x] Build Home with greeting and basic information
- [x] Build Footer with a copyright message and an unordered list with links to other profiles of the author
- [x] Add all components to the app
- [x] Write tests for the components
- [x] Add globalstyles
- [x] Add styles
 
### Complexity (low, medium, high)

low
