### ISSUE TITLE
[US-06] Add search

### ISSUE THREAD

**Issue by saschacollinet** [saschacollinet/capstone-project#8]
### Value Statement (User Story)

As a user
I want to search for activities
in order to display them as a list

### Acceptance criteria

- [x] The search button renders in the header
- [x] On click onto the search button the input field for the search toggles in and out of view
- [x] While typing the results display in main
- [x] The results can still be toggled for details

### Tasks

- [x] Create feature branch
- [x] Build search button
- [x] Build input field
- [x] Implement onclick function to toggle the input field
- [x] Implement filter function to display the results for the entered keyword, use onkeyup event to display results while typing
- [x] Add all compnenets to the app
- [x] Write tests for the components
- [x] Add styles

### Complexity (low, medium, high)

high
